# Generated by Django 2.0.5 on 2019-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
