# Generated by Django 2.0.5 on 2019-01-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='image_upload',
        ),
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
