# Generated by Django 2.0.5 on 2019-01-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20190114_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category (e.g. Ale)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this beer', to='beer.Category'),
        ),
    ]
