# Generated by Django 2.0.5 on 2019-01-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_auto_20190116_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('name', '-added_date')},
        ),
    ]
