# Generated by Django 2.0.5 on 2019-01-18 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beer', '0003_auto_20190116_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerlist',
            name='list_beer',
        ),
        migrations.RemoveField(
            model_name='beerlist',
            name='user',
        ),
        migrations.AddField(
            model_name='beer',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='beers_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Beerlist',
        ),
    ]
