# Generated by Django 2.0.5 on 2019-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20190114_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
