# Generated by Django 2.0.5 on 2019-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_auto_20190118_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='strength',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
