# Generated by Django 2.0.5 on 2019-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
