# Generated by Django 2.0.5 on 2019-01-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0005_auto_20190120_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='users_like',
        ),
        migrations.AddField(
            model_name='like',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Beer'),
        ),
    ]
