# Generated by Django 2.0.5 on 2019-01-21 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beer', '0007_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='beer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
