# Generated by Django 2.0.5 on 2019-01-22 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0008_auto_20190121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
